# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [2]:
import numpy as np
np.__version__

'1.20.3'

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [8]:
arr = np.random.uniform(low=0, high=20, size=(4, 7))
arr2 = np.random.uniform(low=0, high=20, size=(4, 7))

print(arr)
print(arr2)

[[19.99060678  5.51507103 16.74499334 16.51323716  9.00082095 11.50752259
  18.17806792]
 [13.26841541 12.02915348 18.88603532 19.41432265  9.83883863  4.52918549
  16.43156399]
 [19.11245715  4.83473454  6.40513994 17.73283752 15.45441987  1.1287809
   7.23696844]
 [12.99447724  8.04463126  3.12178839 18.2311408   8.13306246  5.21621857
  13.7063788 ]]
[[ 9.85784174  9.71312356 15.52197463  7.06098357 19.99451005  2.37299844
   6.0872907 ]
 [14.55648068 16.29041759 12.46352877  7.01810463  1.13156017  7.33432325
   0.32375689]
 [ 5.45245319  2.33238253  0.78401168 18.53308026  6.82186077  1.02416373
  16.22899789]
 [16.91497139  7.81753798 15.12818677 19.06667781  6.95812761  7.54446233
  18.49661056]]


In [9]:
arr + 100

array([[119.99060678, 105.51507103, 116.74499334, 116.51323716,
        109.00082095, 111.50752259, 118.17806792],
       [113.26841541, 112.02915348, 118.88603532, 119.41432265,
        109.83883863, 104.52918549, 116.43156399],
       [119.11245715, 104.83473454, 106.40513994, 117.73283752,
        115.45441987, 101.1287809 , 107.23696844],
       [112.99447724, 108.04463126, 103.12178839, 118.2311408 ,
        108.13306246, 105.21621857, 113.7063788 ]])

In [10]:
arr + arr2

array([[29.84844851, 15.22819459, 32.26696796, 23.57422072, 28.995331  ,
        13.88052103, 24.26535862],
       [27.8248961 , 28.31957107, 31.34956408, 26.43242728, 10.97039879,
        11.86350874, 16.75532087],
       [24.56491033,  7.16711706,  7.18915162, 36.26591777, 22.27628064,
         2.15294463, 23.46596633],
       [29.90944864, 15.86216924, 18.24997516, 37.29781861, 15.09119007,
        12.76068091, 32.20298936]])

In [11]:
arr.min(), arr.max(), np.min(arr)

(1.1287809006204652, 19.990606777726118, 1.1287809006204652)

In [12]:
(arr - arr.min())/(arr.max()-arr.min())

array([[1.        , 0.23254854, 0.82792687, 0.81563982, 0.41735302,
        0.55025117, 0.90390438],
       [0.64360866, 0.57790654, 0.94143878, 0.96944707, 0.46178232,
        0.18027971, 0.81130974],
       [0.95344302, 0.19647905, 0.27973745, 0.88029954, 0.75950436,
        0.        , 0.32383861],
       [0.62908524, 0.36665858, 0.10566355, 0.90671815, 0.37134695,
        0.21670424, 0.66682823]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [15]:
arr = np.random.randint(low=0, high=10, size=(8,10))
arr

array([[4, 7, 2, 6, 2, 8, 1, 1, 2, 0],
       [7, 9, 2, 1, 8, 6, 6, 0, 7, 6],
       [9, 3, 5, 7, 8, 1, 4, 8, 4, 6],
       [3, 1, 1, 4, 5, 6, 3, 1, 1, 6],
       [2, 9, 8, 3, 7, 7, 7, 4, 4, 8],
       [2, 8, 2, 7, 2, 4, 5, 4, 9, 2],
       [2, 5, 2, 9, 8, 5, 6, 6, 2, 9],
       [5, 5, 1, 4, 7, 5, 9, 8, 9, 6]])

In [16]:
arr[3, 4]

5

In [18]:
arr[:3, 4:8]

array([[2, 8, 1, 1],
       [8, 6, 6, 0],
       [8, 1, 4, 8]])

In [19]:
arr[:, 4:8]

array([[2, 8, 1, 1],
       [8, 6, 6, 0],
       [8, 1, 4, 8],
       [5, 6, 3, 1],
       [7, 7, 7, 4],
       [2, 4, 5, 4],
       [8, 5, 6, 6],
       [7, 5, 9, 8]])

In [21]:
arr.sum(axis=0)  #вдоль нулевой оси - по столбцам

array([34, 47, 23, 41, 47, 42, 41, 32, 38, 43])

In [22]:
sum_by_row = arr.sum(axis=1)
sum_by_row

array([33, 52, 55, 31, 59, 45, 54, 59])

In [24]:
min_row_idx = sum_by_row.argmin()
min_row_idx

3

In [25]:
arr[min_row_idx]

array([3, 1, 1, 4, 5, 6, 3, 1, 1, 6])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [31]:
x = np.array([1, 2, 3])
y = np.array([1, 0, 3])

np.sqrt(np.power(x - y, 2).sum())

2.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [35]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [37]:
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [42]:
A @ X @ B

array([[ -7., -21.],
       [-11.,  -8.],
       [ -8.,  -4.]])

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
arr = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1)
arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [37]:
mean = np.mean(arr[:, 1:], axis = 0)
minarr = np.min(arr[:, 1:], axis = 0)
maxarr = np.max(arr[:, 1:], axis = 0)
median = np.median(arr[:, 1:], axis = 0)

print(mean)
print(minarr)
print(maxarr)
print(median)

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [26]:
tenrecipes = arr[np.random.randint(0, len(arr), size=10)]
print(tenrecipes)

[[133492    120      7]
 [266518     27      9]
 [ 98842   1560     10]
 [ 81875    135     11]
 [172470     40     15]
 [ 33538     40      9]
 [307509     25      5]
 [245986   1470      5]
 [348888     40      8]
 [407643     50     11]]


4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [35]:
arr_five_ingr = arr[arr[:, 2]<=5]
print(arr_five_ingr)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [41]:
arr_lessmean_ingr = arr[arr[:, 2] < mean[1]]
print(100*len(arr_lessmean_ingr)/len(arr), '%')

58.802 %


6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [12]:
arr_new = np.copy(arr)
print(np.quantile(arr[:, 1], q = 0.75))
arr_new[arr[:, 1] > np.quantile(arr[:, 1], q = 0.75) ] = np.quantile(arr[:, 1], q = 0.75)
arr_new

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [    65,     65,     65]])

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [86]:
count_zero = len(arr[arr[:,1] == 0])
arr_new_2  = np.copy(arr)
arr_new_2[arr_new_2[:, 1] == 0] = 1

print(count_zero)
print(arr_new_2)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [75]:
ingr_unique, ingr_unique_counts = np.unique(arr[:,2], return_counts = True)
print(ingr_unique, ingr_unique_counts)

bool_arr = np.isin(np.arange(1, 42), ingr_unique)
np.arange(1, 42)[np.logical_not(bool_arr)]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] [   13   926  2895  5515  7913  9376 10628 10951 10585  9591  8297  6605
  4997  3663  2595  1767  1246   790   573   376   217   161   105    69
    50    28    16    16    12    12     3     1     2     1     3     1
     1]


array([36, 38, 40, 41])

9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [14]:
ingr_for_min = arr[arr[:,1]!=0, 2]/arr[arr[:,1]!=0, 1]
print(ingr_for_min)
print(np.max(ingr_for_min))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
23.0


10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [139]:
top_min = sorted(arr[:,1])[::-1][:100]
top = arr[arr[:, 1] >= top_min[-1], :100]
np.mean(top[:, 2])

6.617647058823529

11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [15]:
condition = np.int32((arr[:, 1] <= 20) & (arr[:, 2] <= 5))
condition = condition.reshape((len(condition), 1))
graded_recipes = np.concatenate((arr, condition), axis = 1)
print(graded_recipes)
print(100*len(graded_recipes[graded_recipes[:,3]==1])/len(graded_recipes), '%')

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]
9.552 %


12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [8]:
short_arr = arr[arr[:, 1] < 10]
standard_arr = arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
long_arr = arr[arr[:, 1] >= 20]

length = np.min([len(short_arr), len(standard_arr), len(long_arr)])
result_arr = np.array([short_arr[:length], standard_arr[:length], long_arr[:length]])
print(result_arr)
print(result_arr.shape)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
(3, 7588, 3)


13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [142]:
numpy = np.array([[5], [10]])
arr[:10][:, 1:]@numpy

array([[460],
       [195],
       [110],
       [ 85],
       [440],
       [270],
       [180],
       [125],
       [125],
       [170]])